/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "You've been hired into your competitor's company. They have a full incremental\n               stack set up, multipliers and all, to increase their net worth. It's your job\n               to infiltrate their company, undermine their systems, and shrink their net worth\n               all the way down to nothing. At the moment you have no knowledge of their systems\n               and no power. You should start by getting a promotion.": "你被你的竞争对手的公司录用了。 他们有一个完整的增量堆栈设置，乘数等等，以增加他们的净资产。 你的工作是\n 渗透到他们的公司，破坏他们的系统，并将他们的净资产\n 缩减到一无所有。 目前你对他们的系统一无所知\n也没有权力。 你应该从升职开始。",
    "You've been hired into your competitor's company. They have a full incremental\n       stack set up, multipliers and all, to increase their net worth. It's your job\n       to infiltrate their company, undermine their systems, and shrink their net worth\n       all the way down to nothing. At the moment you have no knowledge of their systems\n       and no power. You should start by getting a promotion.": "你被你的竞争对手的公司录用了。 他们有一个完整的增量堆栈设置，乘数等等，以增加他们的净资产。 你的工作是\n 渗透到他们的公司，破坏他们的系统，并将他们的净资产\n 缩减到一无所有。 目前你对他们的系统一无所知\n也没有权力。 你应该从升职开始。",
    ": Chat with other players of this and similar games. ": "：与此游戏和类似游戏的其他玩家聊天。",
    ": Please support the author to ensure that more games can be created in the future!": ": 请多多支持作者，保证以后能创作出更多的游戏！",
    "Anthony Toney": "安东尼托尼",
    "Ask the fake employees to make you more popular, or less, or no change (cycle on click)": "要求假员工让你更受欢迎，或者更少，或者没有变化（点击循环）",
    "Charm": "魅力",
    "Company Net Worth": "公司净资产",
    "Credits and Social": "鸣谢和社交",
    "Discord": "不和谐",
    "Fake Employees": "假员工",
    "Follow the suggestions in the lower third of the game": "遵循游戏下三分之一的建议",
    "Game": "游戏",
    "Game by Kygron [": "Kygron的游戏[",
    "Get a promotion": "获得晋升",
    "Hard Reset": "硬重置",
    "Learn how in a mission": "了解如何在任务中",
    "Make yourself less popular, and your actions are more hidden": "让自己不那么受欢迎，你的行为更隐蔽",
    "Make yourself more popular, and your actions are more significant": "让自己更受欢迎，你的行动更有意义",
    "Mission: Work for a promotion": "使命：为升职工作",
    "Missions Complete": "任务完成",
    "newgrounds": "newgrounds",
    "OK": "好的",
    "Other spies that served as stepping stones along your way": "沿途充当垫脚石的其他间谍",
    "Patreon": "帕特伦",
    "Percent of the company who likes you": "喜欢你的公司的百分比",
    "Please join in thanking the following people for supporting this game in development!": "请加入感谢以下人员支持此游戏的开发！",
    "Popularity": "人气",
    "Promotion": "晋升",
    "Rank": "头衔",
    "Relations": "关系",
    "Repulse": "排斥",
    "Scandals": "丑闻",
    "Speak to spies": "与间谍交谈",
    "Suspicion": "怀疑",
    "Thanks to all the players for trying out the game! Please share with your friends!": "感谢所有尝试游戏的玩家！请与您的朋友分享！",
    "The company gains 2x income while trending": "公司在趋势中获得 2 倍的收入",
    "The value of this company, get it down!": "这家公司的价值，拿下来！",
    "This starts the game over from the beginning, removes all progress and achievements. Only use it if the game is corrupted or you want a fresh start.": "这将从头开始游戏，删除所有进度和成就。仅当游戏已损坏或您想要重新开始时才使用它。",
    "Took a bullet": "吃了一颗子弹",
    "Trending - Progress": "趋势 - 进展",
    "twitter": "twitter",
    "When you sabotage the company, people begin to suspect you're a spy, don't let this bar fill!": "当你破坏公司时，人们开始怀疑你是间谍，不要让这个酒吧填满！",
    "Work an entry level job generating ideas, try for promotion": "从事入门级工作，产生想法，尝试晋升",
    "Work+": "工作+",
    "You're a Spy": "你是间谍",
    "Your accomplices, working to topple the company. They're paid well, but manage to avoid company work": "你的同伙，正在努力推翻公司。他们的薪水不错，但设法避免公司工作",
    "Your dealings with the company": "您与公司的交易",
    "Your progress towards a promotion": "您的升职进度",
    "A promotion! You now work creating designs from ideas.\n       More importantly, you have some power to affect their company. You can sabotage\n       products by claiming the designs are flawed. Or other creative ways. You might\n       even be able to convince HR to hire some of your 'friends'.": "晋升！现在，您可以根据想法创建设计。\n更重要的是，你有能力影响他们的公司。您可以通过声称设计有缺陷来破坏产品。或者其他创造性的方式。你甚至可以说服人力资源部雇佣你的一些“朋友”。",
    "Common Products": "普通产品",
    "Convince HR to hire your friends": "说服 HR 雇佣你的朋友",
    "Damage+": "伤害+",
    "Get someone in trouble, eventually": "最终让某人陷入困境",
    "Good Products": "好产品",
    "Great Products": "伟大的产品",
    "Hire+": "雇用+",
    "Mission: Reach 100 Popularity. Speak to your fake employees (spies) for help. Hire more\n       fake employees and charm the real ones. Notice that these buttons have square corners?\n       Hold them down for 10 clicks per second!": "任务：达到 100 人气。 向你的假雇员（间谍）寻求帮助。 雇用更多\n 假员工并吸引真正的员工。 注意到这些按钮有方角吗？\n 按住它们每秒点击 10 次！",
    "Products": "产品",
    "Products with a high profit margin, the main point of attack for saboteurs": "利润率高的产品，破坏者的主要攻击点",
    "Products with a low profit margin, managers work to upgrade these to make them good, faster the more there are": "利润率低的产品，经理们努力升级这些产品，使它们变得更好，越快越好",
    "Products with a medium profit margin, managers work to upgrade these to make them great, faster the more there are": "具有中等利润率的产品，经理们努力升级这些产品，使它们变得更好，越快越好",
    "Reduce good products to common ones": "将好产品降为普通产品",
    "Reduce great products to good ones": "将优质产品简化为好产品",
    "Sabotage+": "破坏+",
    "Switch Labels-": "切换标签-",
    "Time left in trending mode, with 2x income": "趋势模式剩余时间，收入 2 倍",
    "Trending - Happening now!!": "趋势 - 正在发生！",
    "What this company is known for": "这家公司以什么着称",
    "Work a mid-level job designing products, try for promotion": "从事设计产品的中层工作，尝试晋升",
    "Failure! The company you were trying to bankrupt has instead flourished and holds\n       at least 50% of the market. Try to sabotage more of their systems next time. You\n       can also steal more designs, which will give you more time. And now you can reset\n       with a big bonus to that time, because you seem to need it!": "失败！ 你试图破产的公司反而蓬勃发展，并拥有至少 50% 的市场份额。 下次尝试破坏他们的更多系统。 你\n还可以窃取更多的设计，这会给你更多的时间。 现在你可以重置\n，因为你似乎需要它！",
    "Reset with Competitors Bonus": "重置获得竞争对手奖励",
    "Another promotion! Now you work making product plans.\n       And with that comes the opportunity to steal the designs they're based on. If you\n       leak them to the world, it will be harder for this company to gain a monopoly.": "又一次提升！ 现在您开始制定产品计划。\n 随之而来的是窃取他们所基于的设计的机会。 如果你\n将它们泄露给世界，这家公司将更难获得垄断。",
    "Bad Idea-": "馊主意-",
    "Cancel-": "取消-",
    "Common products are created from these, lead by management, faster the more there are": "共同的产品是由这些创造出来的，由管理层领导，越多越快",
    "Designs": "设计",
    "Employees upgrade these to designs, faster the more there are": "员工将这些升级到设计，速度越快",
    "Employees upgrade these to plans, faster the more there are": "员工将这些升级到计划，越多越快",
    "Future potential of the company": "公司未来潜力",
    "Ideas": "想法",
    "Information": "信息",
    "Plans": "计划",
    "Remove an idea from the pool, gain extra suspicion if there are under 10": "从池中删除一个想法，如果少于 10 个，则获得额外的怀疑",
    "Steal Design+": "窃取设计+",
    "Stop all use of a great product, very suspicious": "停止使用一个伟大的产品，非常可疑",
    "Take a design and leak it to the world, increasing competitors net worth": "采用设计并将其泄露给世界，增加竞争对手的净资产",
    "Work a high-level job planing product roll-outs, try for promotion": "高水平工作计划产品推出，尝试提升",
    "You wonder if all this hard work is helping the company more than you'd like. But!\n       With this new promotion into a management position, you have some power over\n       the other employees. Maybe you can distract them from their jobs for a while.\n       In your fake job, you help create new common product lines.": "你想知道所有这些辛勤工作是否对公司的帮助超出了你的想象。 但是！\n 有了这个新的晋升到管理职位，你有一些权力\n 其他员工。 也许你可以暂时分散他们的注意力。\n 在你的假工作中，你帮助创建新的通用产品线。",
    "A low-level management job overseeing common products, try for promotion": "监督普通产品的低级管理工作，尝试晋升",
    "Average Employees": "普通员工",
    "Cause some drama": "引起一些戏剧性",
    "Distracted workers lose productivity": "分心的工人失去生产力",
    "Distraction-": "分心——",
    "Employees": "雇员",
    "Excellent Employees": "优秀员工",
    "Fire-": "解雇-",
    "Good Employees": "好员工",
    "Gossip+": "八卦+",
    "Human resources": "人力资源",
    "Percent of max work being done": "已完成最大工作的百分比",
    "Productivity": "生产率",
    "Reduce suspicion by blaming and firing a fake employee": "通过指责和解雇假员工来减少怀疑",
    "The company pays them poorly to generate ideas": "公司付给他们低薪以产生想法",
    "The company pays them the most to turn designs into plans": "公司付给他们最多的钱来把设计变成计划",
    "The company pays them well to turn ideas into designs": "公司付给他们丰厚的报酬，让他们把想法变成设计",
    "Scandal - Progress": "丑闻 - 进展",
    "You'll have more options during a scandal": "在丑闻期间你会有更多选择",
    "They have promoted you to oversee the improvement of common product lines. This\n        gives you unprecedented access to the company and its technology labs. You\n        immediately start making plans for a flawed product. Of course, you have to work\n        on profitable products too. You're now directly responsible for a small but\n        noticeable improvement in the company's net worth.": "他们提拔你监督共同产品线的改进。 这\n 让您可以前所未有地访问公司及其技术实验室。 您\n 立即开始为有缺陷的产品制定计划。 当然，你也必须在盈利的产品上工作。 您现在直接负责公司净资产的小幅但\n 显着改善。",
    "A mid-level management job improving profitability, try for promotion": "提高盈利能力的中层管理工作，争取晋升",
    "Break Equipment-": "破碎设备-",
    "Change capabilities": "改变能力",
    "Defective Products-": "有缺陷的产品-",
    "IT Training": "信息技术培训",
    "Miscalibrate Products+": "错误校准产品+",
    "Multiplier for info area item development": "信息区域项目开发的乘数",
    "Multiplier for product income": "产品收入乘数",
    "People who improve improvement, well paid": "改善改善的人，高薪",
    "Product $+": "产品 $+",
    "Reduce income multiplier": "降低收入乘数",
    "Reduce IT training, get someone in trouble": "减少 IT 培训，让某人陷入困境",
    "Scientists": "科学家们",
    "Tech": "科技",
    "WARNING! High suspicion!\n          Start a product line that will cost the company money, run by the\n          fake employees": "警告！ 高度怀疑！\n 启动一条将花费公司资金的产品线，由假冒员工经营\n",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);